FROM cuda:9.1-base-ubuntu18.04

RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod bionic main" > /etc/apt/sources.list.d/dotnet.list && \
apt-get update && \
apt-get install -y dotnet-runtime-2.0.7 && \
rm -rf /var/lib/apt/lists/*

CMD ["/bin/sh"]